name: Ricky Brandon
favicon: null
layout_spectrum: 0.13926771469414234
typography_spectrum: 0.04072773223742843
title: Live More Empowered
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.6397159621119499
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
